---
title: "Playground s3e1"
author: "Arnold Kakas"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(rio)
library(tidyverse)
library(patchwork)
library(skimr)
library(corrplot)
library(tidymodels)
library(viridis)
library(GGally)
```

```{r}
train_data <- import("Data/train.csv")
test_data <- import("Data/test.csv")
```

```{r}
skim(train_data)
```
```{r}
skim(test_data)
```

```{r}
train_data %>%
  select(c(2, 3, 4, 5, 6, 7, 8, 9, 10)) %>%
  cor() %>%
  corrplot(method = "number")
```

```{r}
test_data %>%
  select(c(2, 3, 4, 5, 6, 7, 8, 9)) %>%
  cor() %>%
  corrplot(method = "number")
```
```{r}
train_data %>%
  ggplot(mapping = aes(x = Latitude, y = Longitude)) +
  geom_point(aes(size = Population, color = MedHouseVal), alpha = .2) +
  scale_color_viridis(discrete = FALSE, option = "C") +
  scale_fill_viridis(discrete = FALSE) +
  theme_bw()
```

prepare recipe

```{r}
set.seed(123)
house_split <-
  train_data %>%
  select(-c(id)) %>%
  initial_split(strata = MedHouseVal)
house_train <- training(house_split)
house_test <- testing(house_split)

set.seed(234)
house_folds <- vfold_cv(house_train, strata = MedHouseVal)

house_rec <-
  recipe(MedHouseVal ~ ., data = house_train) %>%
  step_BoxCox(c(MedInc, HouseAge, AveRooms, AveBedrms, Population, AveOccup))

xgb_spec <-
  boost_tree(
    trees = tune(),
    tree_depth = tune(), 
    min_n = tune(),
    sample_size = tune(),  ## randomness
    mtry = tune(), ## randomness
    learn_rate = 0.01
  ) %>%
  set_engine("xgboost") %>%
  set_mode("regression")

xgb_grid <- grid_latin_hypercube(
  trees(),
  tree_depth(),
  min_n(),
  sample_size = sample_prop(),
  finalize(mtry(), house_train),
  size = 20
)

xgb_wf <- workflow(house_rec, xgb_spec)
xgb_wf
```

```{r}
library(finetune)
doParallel::registerDoParallel()

set.seed(234)
xgb_house_rs <-
  tune_grid(
    xgb_wf,
    resamples = house_folds,
    grid = xgb_grid,
    control = control_grid(save_pred = TRUE)
  )

xgb_best <- select_best(xgb_house_rs, "rmse")

```

```{r}
xgb_last <-
  xgb_wf %>%
  finalize_workflow(select_best(xgb_house_rs, "rmse")) %>%
  last_fit(house_split)
xgb_last$.metrics
```

```{r}
library(vip)

xgb_fit <- extract_fit_parsnip(xgb_last)
vip(xgb_fit, geom = "point", num_features = 12)
```
```{r}
prediction_xgb_rec <- boost_tree(
    trees = xgb_best$trees,
    tree_depth = xgb_best$tree_depth, 
    min_n = xgb_best$min_n,
    sample_size = xgb_best$sample_size,  ## randomness
    mtry = xgb_best$mtry, ## randomness
    learn_rate = 0.1
  ) %>%
  set_engine("xgboost") %>%
  set_mode("regression")

prediction_xgb_wf <- xgb_wf %>%
  update_model(prediction_xgb_rec)

prediction_xgb_fit <- 
  prediction_xgb_wf %>% 
  fit(house_train)

predictions <- prediction_xgb_fit %>% 
  predict(house_test) %>% 
  bind_cols(house_test)
```

```{r}
result <- prediction_xgb_fit %>% 
  predict(test_data) %>% 
  bind_cols(test_data) %>% 
  select(c(id, .pred)) %>% 
  rename(MedHouseVal = .pred)

export(result, "Data/submission.csv")
```


# https://medium.com/the-data-journal/the-proper-way-to-display-regression-outputs-in-r-4abab45e33d5
